services:
  tomcat-server:
    image: tomcat:9.0
    restart: always
    volumes:
      - ./TiendaVirtualSB-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/sample.war:ro    

  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=sd-tienda
